// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/remedies.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrewService_GetRemedies_FullMethodName    = "/brew.BrewService/GetRemedies"
	BrewService_GetRemedy_FullMethodName      = "/brew.BrewService/GetRemedy"
	BrewService_GetIngredients_FullMethodName = "/brew.BrewService/GetIngredients"
)

// BrewServiceClient is the client API for BrewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrewServiceClient interface {
	GetRemedies(ctx context.Context, in *GetRemediesRequest, opts ...grpc.CallOption) (*GetRemediesResponse, error)
	GetRemedy(ctx context.Context, in *GetRemedyRequest, opts ...grpc.CallOption) (*Remedy, error)
	GetIngredients(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error)
}

type brewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrewServiceClient(cc grpc.ClientConnInterface) BrewServiceClient {
	return &brewServiceClient{cc}
}

func (c *brewServiceClient) GetRemedies(ctx context.Context, in *GetRemediesRequest, opts ...grpc.CallOption) (*GetRemediesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemediesResponse)
	err := c.cc.Invoke(ctx, BrewService_GetRemedies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brewServiceClient) GetRemedy(ctx context.Context, in *GetRemedyRequest, opts ...grpc.CallOption) (*Remedy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Remedy)
	err := c.cc.Invoke(ctx, BrewService_GetRemedy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brewServiceClient) GetIngredients(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngredientsResponse)
	err := c.cc.Invoke(ctx, BrewService_GetIngredients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrewServiceServer is the server API for BrewService service.
// All implementations must embed UnimplementedBrewServiceServer
// for forward compatibility.
type BrewServiceServer interface {
	GetRemedies(context.Context, *GetRemediesRequest) (*GetRemediesResponse, error)
	GetRemedy(context.Context, *GetRemedyRequest) (*Remedy, error)
	GetIngredients(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error)
	mustEmbedUnimplementedBrewServiceServer()
}

// UnimplementedBrewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrewServiceServer struct{}

func (UnimplementedBrewServiceServer) GetRemedies(context.Context, *GetRemediesRequest) (*GetRemediesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemedies not implemented")
}
func (UnimplementedBrewServiceServer) GetRemedy(context.Context, *GetRemedyRequest) (*Remedy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemedy not implemented")
}
func (UnimplementedBrewServiceServer) GetIngredients(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngredients not implemented")
}
func (UnimplementedBrewServiceServer) mustEmbedUnimplementedBrewServiceServer() {}
func (UnimplementedBrewServiceServer) testEmbeddedByValue()                     {}

// UnsafeBrewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrewServiceServer will
// result in compilation errors.
type UnsafeBrewServiceServer interface {
	mustEmbedUnimplementedBrewServiceServer()
}

func RegisterBrewServiceServer(s grpc.ServiceRegistrar, srv BrewServiceServer) {
	// If the following call panics, it indicates UnimplementedBrewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrewService_ServiceDesc, srv)
}

func _BrewService_GetRemedies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemediesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrewServiceServer).GetRemedies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrewService_GetRemedies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrewServiceServer).GetRemedies(ctx, req.(*GetRemediesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrewService_GetRemedy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemedyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrewServiceServer).GetRemedy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrewService_GetRemedy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrewServiceServer).GetRemedy(ctx, req.(*GetRemedyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrewService_GetIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrewServiceServer).GetIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrewService_GetIngredients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrewServiceServer).GetIngredients(ctx, req.(*GetIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrewService_ServiceDesc is the grpc.ServiceDesc for BrewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brew.BrewService",
	HandlerType: (*BrewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemedies",
			Handler:    _BrewService_GetRemedies_Handler,
		},
		{
			MethodName: "GetRemedy",
			Handler:    _BrewService_GetRemedy_Handler,
		},
		{
			MethodName: "GetIngredients",
			Handler:    _BrewService_GetIngredients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remedies.proto",
}
