// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/remedies.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BotanicaService_GetRemedies_FullMethodName    = "/botanica.BotanicaService/GetRemedies"
	BotanicaService_GetRemedy_FullMethodName      = "/botanica.BotanicaService/GetRemedy"
	BotanicaService_GetIngredients_FullMethodName = "/botanica.BotanicaService/GetIngredients"
	BotanicaService_GetForageables_FullMethodName = "/botanica.BotanicaService/GetForageables"
	BotanicaService_GetForageable_FullMethodName  = "/botanica.BotanicaService/GetForageable"
)

// BotanicaServiceClient is the client API for BotanicaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotanicaServiceClient interface {
	// Remedies
	GetRemedies(ctx context.Context, in *GetRemediesRequest, opts ...grpc.CallOption) (*GetRemediesResponse, error)
	GetRemedy(ctx context.Context, in *GetRemedyRequest, opts ...grpc.CallOption) (*Remedy, error)
	GetIngredients(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error)
	// Forageables
	GetForageables(ctx context.Context, in *GetForageablesRequest, opts ...grpc.CallOption) (*GetForageablesResponse, error)
	GetForageable(ctx context.Context, in *GetForageableRequest, opts ...grpc.CallOption) (*Forageable, error)
}

type botanicaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotanicaServiceClient(cc grpc.ClientConnInterface) BotanicaServiceClient {
	return &botanicaServiceClient{cc}
}

func (c *botanicaServiceClient) GetRemedies(ctx context.Context, in *GetRemediesRequest, opts ...grpc.CallOption) (*GetRemediesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemediesResponse)
	err := c.cc.Invoke(ctx, BotanicaService_GetRemedies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botanicaServiceClient) GetRemedy(ctx context.Context, in *GetRemedyRequest, opts ...grpc.CallOption) (*Remedy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Remedy)
	err := c.cc.Invoke(ctx, BotanicaService_GetRemedy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botanicaServiceClient) GetIngredients(ctx context.Context, in *GetIngredientsRequest, opts ...grpc.CallOption) (*GetIngredientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngredientsResponse)
	err := c.cc.Invoke(ctx, BotanicaService_GetIngredients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botanicaServiceClient) GetForageables(ctx context.Context, in *GetForageablesRequest, opts ...grpc.CallOption) (*GetForageablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForageablesResponse)
	err := c.cc.Invoke(ctx, BotanicaService_GetForageables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botanicaServiceClient) GetForageable(ctx context.Context, in *GetForageableRequest, opts ...grpc.CallOption) (*Forageable, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Forageable)
	err := c.cc.Invoke(ctx, BotanicaService_GetForageable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotanicaServiceServer is the server API for BotanicaService service.
// All implementations must embed UnimplementedBotanicaServiceServer
// for forward compatibility.
type BotanicaServiceServer interface {
	// Remedies
	GetRemedies(context.Context, *GetRemediesRequest) (*GetRemediesResponse, error)
	GetRemedy(context.Context, *GetRemedyRequest) (*Remedy, error)
	GetIngredients(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error)
	// Forageables
	GetForageables(context.Context, *GetForageablesRequest) (*GetForageablesResponse, error)
	GetForageable(context.Context, *GetForageableRequest) (*Forageable, error)
	mustEmbedUnimplementedBotanicaServiceServer()
}

// UnimplementedBotanicaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotanicaServiceServer struct{}

func (UnimplementedBotanicaServiceServer) GetRemedies(context.Context, *GetRemediesRequest) (*GetRemediesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemedies not implemented")
}
func (UnimplementedBotanicaServiceServer) GetRemedy(context.Context, *GetRemedyRequest) (*Remedy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRemedy not implemented")
}
func (UnimplementedBotanicaServiceServer) GetIngredients(context.Context, *GetIngredientsRequest) (*GetIngredientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngredients not implemented")
}
func (UnimplementedBotanicaServiceServer) GetForageables(context.Context, *GetForageablesRequest) (*GetForageablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForageables not implemented")
}
func (UnimplementedBotanicaServiceServer) GetForageable(context.Context, *GetForageableRequest) (*Forageable, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForageable not implemented")
}
func (UnimplementedBotanicaServiceServer) mustEmbedUnimplementedBotanicaServiceServer() {}
func (UnimplementedBotanicaServiceServer) testEmbeddedByValue()                         {}

// UnsafeBotanicaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotanicaServiceServer will
// result in compilation errors.
type UnsafeBotanicaServiceServer interface {
	mustEmbedUnimplementedBotanicaServiceServer()
}

func RegisterBotanicaServiceServer(s grpc.ServiceRegistrar, srv BotanicaServiceServer) {
	// If the following call panics, it indicates UnimplementedBotanicaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BotanicaService_ServiceDesc, srv)
}

func _BotanicaService_GetRemedies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemediesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotanicaServiceServer).GetRemedies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotanicaService_GetRemedies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotanicaServiceServer).GetRemedies(ctx, req.(*GetRemediesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotanicaService_GetRemedy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemedyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotanicaServiceServer).GetRemedy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotanicaService_GetRemedy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotanicaServiceServer).GetRemedy(ctx, req.(*GetRemedyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotanicaService_GetIngredients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngredientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotanicaServiceServer).GetIngredients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotanicaService_GetIngredients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotanicaServiceServer).GetIngredients(ctx, req.(*GetIngredientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotanicaService_GetForageables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForageablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotanicaServiceServer).GetForageables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotanicaService_GetForageables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotanicaServiceServer).GetForageables(ctx, req.(*GetForageablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotanicaService_GetForageable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForageableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotanicaServiceServer).GetForageable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BotanicaService_GetForageable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotanicaServiceServer).GetForageable(ctx, req.(*GetForageableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BotanicaService_ServiceDesc is the grpc.ServiceDesc for BotanicaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotanicaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "botanica.BotanicaService",
	HandlerType: (*BotanicaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRemedies",
			Handler:    _BotanicaService_GetRemedies_Handler,
		},
		{
			MethodName: "GetRemedy",
			Handler:    _BotanicaService_GetRemedy_Handler,
		},
		{
			MethodName: "GetIngredients",
			Handler:    _BotanicaService_GetIngredients_Handler,
		},
		{
			MethodName: "GetForageables",
			Handler:    _BotanicaService_GetForageables_Handler,
		},
		{
			MethodName: "GetForageable",
			Handler:    _BotanicaService_GetForageable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remedies.proto",
}
