// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/remedies.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ingredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ingredient) Reset() {
	*x = Ingredient{}
	mi := &file_proto_remedies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ingredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ingredient) ProtoMessage() {}

func (x *Ingredient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ingredient.ProtoReflect.Descriptor instead.
func (*Ingredient) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{0}
}

func (x *Ingredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ingredient) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Ingredient) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type Remedy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Ingredients   []*Ingredient          `protobuf:"bytes,6,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Properties    []string               `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty"`
	Preparation   string                 `protobuf:"bytes,8,opt,name=preparation,proto3" json:"preparation,omitempty"`
	Notes         string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Remedy) Reset() {
	*x = Remedy{}
	mi := &file_proto_remedies_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remedy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remedy) ProtoMessage() {}

func (x *Remedy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remedy.ProtoReflect.Descriptor instead.
func (*Remedy) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{1}
}

func (x *Remedy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Remedy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Remedy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Remedy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Remedy) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Remedy) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Remedy) GetProperties() []string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Remedy) GetPreparation() string {
	if x != nil {
		return x.Preparation
	}
	return ""
}

func (x *Remedy) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type GetRemediesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Property      string                 `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemediesRequest) Reset() {
	*x = GetRemediesRequest{}
	mi := &file_proto_remedies_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemediesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemediesRequest) ProtoMessage() {}

func (x *GetRemediesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemediesRequest.ProtoReflect.Descriptor instead.
func (*GetRemediesRequest) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{2}
}

func (x *GetRemediesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetRemediesRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type GetRemediesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Remedies      []*Remedy              `protobuf:"bytes,2,rep,name=remedies,proto3" json:"remedies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemediesResponse) Reset() {
	*x = GetRemediesResponse{}
	mi := &file_proto_remedies_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemediesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemediesResponse) ProtoMessage() {}

func (x *GetRemediesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemediesResponse.ProtoReflect.Descriptor instead.
func (*GetRemediesResponse) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{3}
}

func (x *GetRemediesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRemediesResponse) GetRemedies() []*Remedy {
	if x != nil {
		return x.Remedies
	}
	return nil
}

type GetRemedyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemedyRequest) Reset() {
	*x = GetRemedyRequest{}
	mi := &file_proto_remedies_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemedyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemedyRequest) ProtoMessage() {}

func (x *GetRemedyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemedyRequest.ProtoReflect.Descriptor instead.
func (*GetRemedyRequest) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{4}
}

func (x *GetRemedyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetIngredientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientsRequest) Reset() {
	*x = GetIngredientsRequest{}
	mi := &file_proto_remedies_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsRequest) ProtoMessage() {}

func (x *GetIngredientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsRequest.ProtoReflect.Descriptor instead.
func (*GetIngredientsRequest) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{5}
}

type GetIngredientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Ingredients   []string               `protobuf:"bytes,2,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientsResponse) Reset() {
	*x = GetIngredientsResponse{}
	mi := &file_proto_remedies_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsResponse) ProtoMessage() {}

func (x *GetIngredientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remedies_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsResponse.ProtoReflect.Descriptor instead.
func (*GetIngredientsResponse) Descriptor() ([]byte, []int) {
	return file_proto_remedies_proto_rawDescGZIP(), []int{6}
}

func (x *GetIngredientsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetIngredientsResponse) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

var File_proto_remedies_proto protoreflect.FileDescriptor

const file_proto_remedies_proto_rawDesc = "" +
	"\n" +
	"\x14proto/remedies.proto\x12\x04brew\"N\n" +
	"\n" +
	"Ingredient\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\x86\x02\n" +
	"\x06Remedy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x122\n" +
	"\vingredients\x18\x06 \x03(\v2\x10.brew.IngredientR\vingredients\x12\x1e\n" +
	"\n" +
	"properties\x18\a \x03(\tR\n" +
	"properties\x12 \n" +
	"\vpreparation\x18\b \x01(\tR\vpreparation\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\"D\n" +
	"\x12GetRemediesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bproperty\x18\x02 \x01(\tR\bproperty\"U\n" +
	"\x13GetRemediesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12(\n" +
	"\bremedies\x18\x02 \x03(\v2\f.brew.RemedyR\bremedies\"\"\n" +
	"\x10GetRemedyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x17\n" +
	"\x15GetIngredientsRequest\"P\n" +
	"\x16GetIngredientsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12 \n" +
	"\vingredients\x18\x02 \x03(\tR\vingredients2\xd1\x01\n" +
	"\vBrewService\x12B\n" +
	"\vGetRemedies\x12\x18.brew.GetRemediesRequest\x1a\x19.brew.GetRemediesResponse\x121\n" +
	"\tGetRemedy\x12\x16.brew.GetRemedyRequest\x1a\f.brew.Remedy\x12K\n" +
	"\x0eGetIngredients\x12\x1b.brew.GetIngredientsRequest\x1a\x1c.brew.GetIngredientsResponseB#Z!github.com/ricocynthia/brew/protob\x06proto3"

var (
	file_proto_remedies_proto_rawDescOnce sync.Once
	file_proto_remedies_proto_rawDescData []byte
)

func file_proto_remedies_proto_rawDescGZIP() []byte {
	file_proto_remedies_proto_rawDescOnce.Do(func() {
		file_proto_remedies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_remedies_proto_rawDesc), len(file_proto_remedies_proto_rawDesc)))
	})
	return file_proto_remedies_proto_rawDescData
}

var file_proto_remedies_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_remedies_proto_goTypes = []any{
	(*Ingredient)(nil),             // 0: brew.Ingredient
	(*Remedy)(nil),                 // 1: brew.Remedy
	(*GetRemediesRequest)(nil),     // 2: brew.GetRemediesRequest
	(*GetRemediesResponse)(nil),    // 3: brew.GetRemediesResponse
	(*GetRemedyRequest)(nil),       // 4: brew.GetRemedyRequest
	(*GetIngredientsRequest)(nil),  // 5: brew.GetIngredientsRequest
	(*GetIngredientsResponse)(nil), // 6: brew.GetIngredientsResponse
}
var file_proto_remedies_proto_depIdxs = []int32{
	0, // 0: brew.Remedy.ingredients:type_name -> brew.Ingredient
	1, // 1: brew.GetRemediesResponse.remedies:type_name -> brew.Remedy
	2, // 2: brew.BrewService.GetRemedies:input_type -> brew.GetRemediesRequest
	4, // 3: brew.BrewService.GetRemedy:input_type -> brew.GetRemedyRequest
	5, // 4: brew.BrewService.GetIngredients:input_type -> brew.GetIngredientsRequest
	3, // 5: brew.BrewService.GetRemedies:output_type -> brew.GetRemediesResponse
	1, // 6: brew.BrewService.GetRemedy:output_type -> brew.Remedy
	6, // 7: brew.BrewService.GetIngredients:output_type -> brew.GetIngredientsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_remedies_proto_init() }
func file_proto_remedies_proto_init() {
	if File_proto_remedies_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_remedies_proto_rawDesc), len(file_proto_remedies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_remedies_proto_goTypes,
		DependencyIndexes: file_proto_remedies_proto_depIdxs,
		MessageInfos:      file_proto_remedies_proto_msgTypes,
	}.Build()
	File_proto_remedies_proto = out.File
	file_proto_remedies_proto_goTypes = nil
	file_proto_remedies_proto_depIdxs = nil
}
